services:
  postgres:
    image: postgres:15-alpine
    container_name: secureloan-api-postgres
    restart: always
    environment:
      POSTGRES_DB: secureloan-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - secureloan_postgres_data:/var/lib/postgresql/data
    networks:
      - secureloan-api-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d secureloan-api"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: secureloan-api-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - secureloan_redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - secureloan-api-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: secureloan-api-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - secureloan-api-network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  secureloan-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secureloan-api-app
    restart: always
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/secureloan-api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      REDIS_HOST: redis
      REDIS_PORT: 6379

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - secureloan-api-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: secureloan-notification-service
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - secureloan-api-network

volumes:
  secureloan_postgres_data:
    driver: local
  secureloan_redis_data:
    driver: local

networks:
  secureloan-api-network:
    driver: bridge