services:
  postgres:
    image: postgres:15-alpine
    container_name: secureloan-api-postgres
    restart: always
    environment:
      POSTGRES_DB: secureloan-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - secureloan_postgres_data:/var/lib/postgresql/data
    networks:
      - secureloan-api-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: secureloan-api-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - secureloan-api-network

volumes:
  secureloan_postgres_data:
    driver: local

networks:
  secureloan-api-network:
    driver: bridge